# Generated by Django 3.0.4 on 2020-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
