# Generated by Django 3.0.4 on 2020-04-03 16:47

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20200403_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades del empleado'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=django_ckeditor_5.fields.CKEditor5Field(default='texto', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empelado'),
        ),
    ]
